app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("expenses.urls")),
    path("authentication/", include("authentication.urls")),
    path("income/", include("userincome.urls")),
    path("perferences/", include("userpreferences.urls")),
]

expenses/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = "expenses"
urlpatterns = [
    path("", views.index, name="expenses"),
    path("add_expense/", views.add_expenses, name="add_expenses"),
    path("edit_expense/<int:id>", views.edit_expenses, name="edit_expenses"),
    path("delete_expense/<int:id>", views.delete_expenses, name="delete_expenses"),
    path("search_expenses", csrf_exempt(views.search_expenses), name="search_expenses"),
]

userincome/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = "income"
urlpatterns = [
    path("", views.index, name="income"),
    path("add_income/", views.add_income, name="add_income"),
    path("edit_income/<int:id>", views.edit_income, name="edit_income"),
    path("delete_income/<int:id>", views.delete_income, name="delete_income"),
    path("search_income", csrf_exempt(views.search_income), name="search_income"),
]

userpreferences/urls.py
from django.urls import path
from . import views

app_name = "userpreferences"
urlpatterns = [
    path("", views.index, name="preferences"),
]

templates/partials/_messages.html
{% if messages %}
<div class="messages">
	{% for message in messages %}
	<div{% if message.tags %} class="alert alert-sm alert-{{ message.tags }}" {% endif %}>
		{{ message }}
</div>
{% endfor %}
</div>
{% endif %}

templates/partials/_sidebar.html
{% load static %}
<div class="sidebar border border-right col-md-3 col-lg-2 p-0 bg-body-tertiary">
	<div class="offcanvas-md offcanvas-end bg-body-tertiary" tabindex="-1" id="sidebarMenu"
		aria-labelledby="sidebarMenuLabel">
		<div class="offcanvas-header">
			<h5 class="offcanvas-title" id="sidebarMenuLabel">Company name</h5>
			<button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#sidebarMenu"
				aria-label="Close"></button>
		</div>
		<div class="offcanvas-body d-md-flex flex-column p-0 pt-lg-3 overflow-y-auto">
			<ul class="nav flex-column">
				<li class="nav-item">
					<a class="nav-link d-flex align-items-center gap-2 active" aria-current="page" href="#">
						<svg class="bi">
							<use xlink:href="#house-fill"></use>
						</svg>
						Dashboard
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link d-flex align-items-center gap-2" href="{% url 'expenses:expenses' %}">
						Expenses
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link d-flex align-items-center gap-2" href="{% url 'income:income' %}">
						Income
					</a>
				</li>

			</ul>

			<h6
				class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-body-secondary text-uppercase">
				<span>Summary</span>
				<a class="link-secondary" href="#" aria-label="Add a new report">
				</a>
			</h6>
			<ul class="nav flex-column mb-auto">
				<li class="nav-item">
					<a class="nav-link d-flex align-items-center gap-2" href="#">
						Expenses Summary
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link d-flex align-items-center gap-2" href="#">
						Income Summary
					</a>
				</li>

			</ul>
			<h6
				class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-body-secondary text-uppercase">
				<span>Settings</span>
				<a class="link-secondary" href="#" aria-label="Add a new report">
				</a>
			</h6>
			<ul class="nav flex-column mb-auto">
				<li class="nav-item">
					<a class="nav-link d-flex align-items-center gap-2" href="{% url 'userpreferences:preferences' %}">
						General
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link d-flex align-items-center gap-2" href="">
						Account
					</a>
				</li>

			</ul>

		</div>
	</div>
</div>