app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("expenses.urls")),
    path("authentication/", include("authentication.urls")),
    path("income/", include("userincome.urls")),
    path("perferences/", include("userpreferences.urls")),
]

userincome/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = "income"
urlpatterns = [
    path("", views.index, name="income"),
    path("add_income/", views.add_income, name="add_income"),
    path("edit_income/<int:id>", views.edit_income, name="edit_income"),
    path("delete_income/<int:id>", views.delete_income, name="delete_income"),
    path("search_income", csrf_exempt(views.search_income), name="search_income"),
]

templates/income/add_income.html
{% extends 'base.html' %}


{% block content %}
<div class="container mt-4">
	<nav aria-label="breadcrumb">
		<ol class="breadcrumb p-3 bg-body-tertiary rounded-3">
			<li class="breadcrumb-item"><a href="{% url 'income:income' %}">Income</a></li>
			<li class=" breadcrumb-item active"><a href="{% url 'income:add_income' %}" aria-current=" page">Add
					Income</a>
			</li>
		</ol>
	</nav>

	<div class="card">
		<div class="card-body">
			<form action="{% url 'income:add_income' %}" method="post">
				{% include 'partials/_messages.html' %}
				{% csrf_token %}
				<div class="form-group">
					<label for="">Amount</label>
					<input value="{{values.amount}}" type="number" class="form-control form-control-sm" name="amount">
				</div>
				<div class="form-group my-3">
					<label for="">Description</label>
					<input value="{{values.description}}" type="text" class="form-control form-control-sm"
						name="description">
				</div>
				<div class="form-group">
					<label for="">Sources</label>
					<select class="form-control" name="source" id="">
						{% for source in sources %}
						<option name="source" value="{{source.name}}">{{source.name}}</option>
						{% endfor %}
					</select>
				</div>
				<div class="form-group my-3">
					<label for="">Date of Income</label>
					<input type="date" class="form-control form-control-sm my-3" name="date">
				</div>

				<input type="submit" value="Submit" class="btn btn-primary btn-primary-sm">
			</form>
		</div>
	</div>
</div>
{% endblock %}

templates/income/edit_income.html
{% extends 'base.html' %}


{% block content %}
<div class="container mt-4">
	<div class="row">
		<div class="col-md-10">
			<nav aria-label="breadcrumb">
				<ol class="breadcrumb p-3 bg-body-tertiary rounded-3">
					<li class="breadcrumb-item"><a href="{% url 'income:income' %}">Income</a></li>
					<li class=" breadcrumb-item active"><a href="{% url 'income:add_income' %}"
							aria-current=" page">Edit
							Income</a>
					</li>
				</ol>
			</nav>
		</div>
		<div class="col-md-2">
			<a href="{% url 'income:delete_income' income.id %}" class="btn btn-sm btn-danger">Delete</a>
		</div>
	</div>


	<div class="card">
		<div class="card-body">
			<form action="{% url 'income:edit_income' income.id %}" method="post">
				{% include 'partials/_messages.html' %}
				{% csrf_token %}
				<div class="form-group">
					<label for="">Amount</label>
					<input value="{{values.amount}}" type="number" class="form-control form-control-sm" name="amount">
				</div>
				<div class="form-group my-3">
					<label for="">Description</label>
					<input value="{{values.description}}" type="text" class="form-control form-control-sm"
						name="description">
				</div>
				<div class="form-group">
					<label for="">Source</label>
					<select class="form-control" name="source" id="">
						{% for source in sources %}
						<option selected name="source" value="{{values.source}}">{{values.source}}
						</option>
						<option name="source" value="{{source.name}}">{{source.name}}</option>
						{% endfor %}
					</select>
				</div>
				<div class="form-group my-3">
					<label for="">Date of Income</label>
					<input type="date" value="{{values.date |date:'Y-m-d'}}" class="form-control form-control-sm my-3"
						name="date">
				</div>

				<input type="submit" value="Save" class="btn btn-primary btn-sm">
			</form>
		</div>
	</div>
</div>
{% endblock %}

templates/income/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-4">
	<div class="row">

		<div class="col-md-10">
			<nav aria-label="breadcrumb">
				<ol class="breadcrumb p-3 bg-body-tertiary rounded-3">
					<li class="breadcrumb-item active"><a href="{% url 'income:income' %}"
							aria-current="page">Income</a>
					</li>
					<li class="breadcrumb-item"><a href="{% url 'income:add_income' %}">My Income</a></li>
				</ol>
			</nav>
		</div>
		<div class="col-md-2">
			<a href="{% url 'income:add_income' %}" class="btn btn-primary btn-sm">Add Income</a>
		</div>
	</div>
	<div class="container">
		{% include 'partials/_messages.html' %}
		{% if income.count %}
		<div class="row">
			<div class="col-md-8"></div>
			<div class="col-md-4">
				<div class="form-group">
					<input type="text" class="form-control" placeholder="Search" id="searchField">
				</div>
			</div>
		</div>

		<div class="app-table">
			<table class="table table-stripped table-hover">
				<thead>
					<tr>
						<th>
							Amount ({{currency}})
						</th>
						<th>
							Source

						</th>
						<th>
							Description
						</th>
						<th>
							Date
						</th>
						<th>

						</th>
					</tr>
				</thead>
				<tbody>
					{% for income in page_obj %}
					<tr>
						<td>{{income.amount}}</td>
						<td>{{income.source}}</td>
						<td>{{income.description}}</td>
						<td>{{income.date}}</td>
						<td>

							<a href="{% url 'income:edit_income' income.id %}" class="btn btn-sm btn-secondary">Edit</a>
							<a href="{% url 'income:delete_income' income.id %}"
								class="btn btn-sm btn-danger">Delete</a>
						</td>

					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>

		<div class="table-output">
			<table class="table table-stripped table-hover">
				<thead>
					<tr>
						<th>
							Amount ({{currency}})
						</th>
						<th>
							Source
						</th>
						<th>
							Description
						</th>
						<th>
							Date
						</th>
						<th>

						</th>
					</tr>
				</thead>
				<tbody class="table-body">

				</tbody>
			</table>
		</div>
		<div class="pagination-container">
			<div class="">
				Showing page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
			</div>

			<ul class="pagination d-flex justify-content-end">
				{% if page_obj.has_previous %}
				<li class="{% if page_obj.number == 1 %} page-item  active{% endif %}">
					<a href="?page=1" class="page-link">&laquo; 1</a>
				</li>
				<li class="page-item">
					<a href="?page={{ page_obj.previous_page_number }}" class="page-link">Previous</a>
				</li>

				{% endif %}

				{% if page_obj.has_next %}
				<li class="page-item ">
					<a href="?page={{ page_obj.next_page_number}}" class=" page-link">Next</a>
				</li>
				<li class="page-item ">
					<a href="?page={{ page_obj.paginator.num_pages}}" class="page-link">
						{{ page_obj.paginator.num_pages }} &raquo;
					</a>
				</li>
				{% endif %}

			</ul>
		</div>
		{% endif %}
	</div>
</div>
<script src="{% static 'js/searchIncome.js' %}"></script>
{% endblock %}