app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("expenses.urls")),
    path("authentication/", include("authentication.urls")),
    path("income/", include("userincome.urls")),
    path("perferences/", include("userpreferences.urls")),
]

expenses/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = "expenses"
urlpatterns = [
    path("", views.index, name="expenses"),
    path("add_expense/", views.add_expenses, name="add_expenses"),
    path("edit_expense/<int:id>", views.edit_expenses, name="edit_expenses"),
    path("delete_expense/<int:id>", views.delete_expenses, name="delete_expenses"),
    path("search_expenses", csrf_exempt(views.search_expenses), name="search_expenses"),
]

expenses/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User


# Create your models here.
class Expense(models.Model):
    amount = models.FloatField()
    date = models.DateField(default=now)
    description = models.TextField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.CharField(max_length=266)

    def __str__(self):
        return self.category

    class Meta:
        ordering = ["-date"]


class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

expenses/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils import timezone
from django.contrib import messages
from .models import Category, Expense


# Create your views here.
@login_required(login_url=reverse_lazy("authentication:login"))
def index(request):
    expenses = Expense.objects.filter(owner=request.user)
    context = {
        "expenses": expenses,
    }
    return render(request, "expenses/index.html", context)


def add_expenses(request):
    categories = Category.objects.all()
    context = {
        "categories": categories,
        "values": request.POST,
    }
    if request.method == "POST":
        amount = request.POST["amount"]
        description = request.POST["description"]
        category = request.POST["category"]
        date = request.POST["date"]

        if not amount:
            messages.error(request, "Amount is required")
            return render(request, "expenses/add_expenses.html", context)
        if not description:
            messages.error(request, "Description is required")
            return render(request, "expenses/add_expenses.html", context)
        if not date:
            date = timezone.now()
        Expense.objects.create(
            owner=request.user,
            amount=amount,
            description=description,
            category=category,
            date=date,
        )
        messages.success(request, "Expense saved successfully")
        return redirect("expenses:expenses")

    return render(request, "expenses/add_expenses.html", context)


def edit_expenses(request, id):
    expense = Expense.objects.get(pk=id)
    categories = Category.objects.all()
    context = {
        "expense": expense,
        "values": expense,
        "categories": categories,
    }
    if request.method == "POST":
        amount = request.POST["amount"]
        description = request.POST["description"]
        category = request.POST["category"]
        date = request.POST["date"]

        if not amount:
            messages.error(request, "Amount is required")
            return render(request, "expenses/edit_expenses.html", context)
        if not description:
            messages.error(request, "Description is required")
            return render(request, "expenses/edit_expenses.html", context)
        if not date:
            date = expense.date

        expense.owner = request.user
        expense.amount = amount
        expense.description = description
        expense.category = category
        expense.date = date
        expense.save()
        messages.success(request, "Expense updated successfully")
        return redirect("expenses:expenses")
    # import pdb

    # pdb.set_trace()
    return render(request, "expenses/edit_expenses.html", context)


def delete_expenses(request, id):
    expense = Expense.objects.get(pk=id)
    expense.delete()
    messages.success(request, "Expense Deleted")
    return redirect("expenses:expenses")

templates/expenses/add_expenses.html
{% extends 'base.html' %}
{% block content %}
<h1>Add Expenses</h1>
{% endblock  %}

templates/expenses/edit_expenses.html
{% extends 'base.html' %}


{% block content %}
<div class="container mt-4">
	<div class="row">
		<div class="col-md-10">
			<nav aria-label="breadcrumb">
				<ol class="breadcrumb p-3 bg-body-tertiary rounded-3">
					<li class="breadcrumb-item"><a href="{% url 'expenses:expenses' %}">Expenses</a></li>
					<li class=" breadcrumb-item active"><a href="{% url 'expenses:add_expenses' %}"
							aria-current=" page">Edit
							Expenses</a>
					</li>
				</ol>
			</nav>
		</div>
		<div class="col-md-2">
			<a href="{% url 'expenses:delete_expenses' expense.id %}" class="btn btn-sm btn-danger">Delete</a>
		</div>
	</div>


	<div class="card">
		<div class="card-body">
			<form action="{% url 'expenses:edit_expenses' expense.id %}" method="post">
				{% include 'partials/_messages.html' %}
				{% csrf_token %}
				<div class="form-group">
					<label for="">Amount</label>
					<input value="{{values.amount}}" type="number" class="form-control form-control-sm" name="amount">
				</div>
				<div class="form-group my-3">
					<label for="">Description</label>
					<input value="{{values.description}}" type="text" class="form-control form-control-sm"
						name="description">
				</div>
				<div class="form-group">
					<label for="">Category</label>
					<select class="form-control" name="category" id="">
						{% for category in categories %}
						<option selected name="category" value="{{values.category}}">{{values.category}}
						</option>
						<option name="category" value="{{category.name}}">{{category.name}}</option>
						{% endfor %}
					</select>
				</div>
				<div class="form-group my-3">
					<label for="">Date of Expense</label>
					<input type="date" class="form-control form-control-sm my-3" name="date">
				</div>

				<input type="submit" value="Save" class="btn btn-primary btn-sm">
			</form>
		</div>
	</div>
</div>
{% endblock %}

templates/expenses/index.html
{% extends 'base.html' %}


{% block content %}
<div class="container mt-4">
	<div class="row">

		<div class="col-md-10">
			<nav aria-label="breadcrumb">
				<ol class="breadcrumb p-3 bg-body-tertiary rounded-3">
					<li class="breadcrumb-item active"><a href="{% url 'expenses:expenses' %}"
							aria-current="page">Expenses</a>
					</li>
					<li class="breadcrumb-item"><a href="{% url 'expenses:add_expenses' %}">Add Expenses</a></li>
				</ol>
			</nav>
		</div>
		<div class="col-md-2">
			<a href="{% url 'expenses:add_expenses' %}" class="btn btn-primary btn-sm">Add Expenses</a>
		</div>
	</div>
	{% include 'partials/_messages.html' %}
	<div class="container">
		{% if expenses.count %}
		<table class="table table-stripped table-hover">
			<thead>
				<tr>
					<th>
						Amount (CURRENCY)
					</th>
					<th>
						Category
					</th>
					<th>
						Description
					</th>
					<th>
						Date
					</th>
					<th>

					</th>
				</tr>
			</thead>
			<tbody>
				{% for expense in expenses %}
				<tr>
					<td>{{expense.amount}}</td>
					<td>{{expense.category}}</td>
					<td>{{expense.description}}</td>
					<td>{{expense.date}}</td>
					<td>

						<a href="{% url 'expenses:edit_expenses' expense.id %}"
							class="btn btn-sm btn-secondary">Edit</a>
						<a href="{% url 'expenses:delete_expenses' expense.id %}"
							class="btn btn-sm btn-danger">Delete</a>
					</td>

				</tr>
				{% endfor %}
			</tbody>
		</table>
		{% endif %}
	</div>
</div>
{% endblock %}