app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("expenses.urls")),
    path("authentication/", include("authentication.urls")),
    path("income/", include("userincome.urls")),
    path("perferences/", include("userpreferences.urls")),
]

authentication/urls.py
from django.urls import path
from .views import (
    RegistrationView,
    LoginView,
    Logout,
    UsernameValidation,
    EmailValidation,
    Verification,
)
from django.views.decorators.csrf import csrf_exempt

app_name = "authentication"
urlpatterns = [
    path("register/", RegistrationView.as_view(), name="register"),
    path(
        "validate_username/",
        csrf_exempt(UsernameValidation.as_view()),
        name="validate_username",
    ),
    path(
        "validate_email/",
        csrf_exempt(EmailValidation.as_view()),
        name="validate_email",
    ),
    path("activate/<uidb64>/<token>", Verification.as_view(), name="activate"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", Logout.as_view(), name="logout"),
]

authentication/models.py
from django.db import models

# Create your models here.

authentication/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.mail import send_mail
from django.utils.encoding import force_bytes, force_str, DjangoUnicodeDecodeError
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth import authenticate, login, logout
from decouple import config
import json
from validate_email import validate_email
from .utils import account_activation_token


class RegistrationView(View):
    def get(self, request):
        return render(request, "authentication/register.html")

    def post(self, request):
        data = request.POST
        username = data["username"]
        email = data["email"]
        password = data["password"]

        context = {
            "fieldValues": request.POST,
        }

        if len(password) < 6:
            messages.error(request, "Password too short")
            return render(request, "authentication/register.html", context)

        user = User.objects.create_user(username=username, email=email)
        user.set_password(password)
        user.is_active = False
        user.save()

        # converting the user.pk to byte string then encoding it for safe page through the url
        uidb64 = urlsafe_base64_encode(force_bytes(user.pk))
        domain = get_current_site(request).domain
        link = reverse(
            "authentication:activate",
            kwargs={
                "uidb64": uidb64,
                "token": account_activation_token.make_token(user),
            },
        )

        activate_url = f"http://{domain}{link}"
        email_subject = "Activate your account"
        email_body = f"Hi {user.username} Please use this link to verify your account \n{activate_url}"
        email = send_mail(
            email_subject,
            email_body,
            "emailtest119@yahoo.com",
            [email],
            fail_silently=False,
        )

        messages.success(request, "Account successfuly created")
        return render(request, "authentication/register.html")


class Verification(View):

    def get(self, request, uidb64, token):
        try:
            id = force_str(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=id)

            if not account_activation_token.check_token(user, token):
                return redirect(f"authentication:login?message=User already activated")

            if user.is_active:
                return redirect("authentication:login")
            else:
                user.is_active = True
                user.save()

                messages.success(request, "Account activated successfully")
                return redirect("authentication:login")

        except Exception as e:
            pass
        return redirect("authentication:login")


class LoginView(View):
    def get(self, request):
        return render(request, "authentication/login.html")

    def post(self, request):
        username = request.POST["username"]
        password = request.POST["password"]

        if username and password:
            user = authenticate(username=username, password=password)

            if user:
                if user.is_active:
                    login(request, user)
                    messages.success(
                        request, f"Welcome, {user.username}, You are now logged in"
                    )
                    return redirect("expenses:expenses")
                else:
                    messages.error(
                        request, "Account not active,, please check your email"
                    )
                    return render(request, "authentication/login.html")
            messages.error(request, "Invalid Credentials, Try again")
            return render(request, "authentication/login.html")
        messages.error(request, "Fill all fields")
        return render(request, "authentication/login.html")


class Logout(View):
    def post(self, request):
        logout(request)
        messages.success(request, "You are been logged out")
        return redirect("authentication:login")


class UsernameValidation(View):
    def post(self, request):
        data = json.loads(request.body)
        username = data["username"]
        if not str(username).isalnum():
            return JsonResponse(
                {
                    "username_error": "username should only contain alphanumeric character",
                },
                status=400,
            )

        if User.objects.filter(username=username).exists():
            return JsonResponse(
                {
                    "username_error": "sorry, username in use, choose another one",
                },
                status=400,
            )
        return JsonResponse({"username_valid": True})


class EmailValidation(View):
    def post(self, request):
        data = json.loads(request.body)
        email = data["email"]
        if not validate_email(email):
            return JsonResponse(
                {
                    "email_error": "Email is invalid",
                },
                status=400,
            )

        if User.objects.filter(email=email).exists():
            return JsonResponse(
                {
                    "email_error": "sorry, email in use, choose another one",
                },
                status=400,
            )
        return JsonResponse({"email_valid": True})

templates/authentication/login.html
{% extends 'base_auth.html' %}
{% load static %}

{% block content %}
<div class='row'>
	<div class='col-md-4'></div>
	<div class='col-md-4'>
		<div class="card mt-5">

			<div class="card-body">
				<div class="card-title py-3">
					<h4>Login to your account</h4>
				</div>
				{% include 'partials/_messages.html' %}
				<form action="{% url 'authentication:login' %}" method="post">
					{% csrf_token %}
					<div class="form-group">
						<input type="text" name="username" id="usernameField" class="form-control form-control-sm"
							placeholder="Username" value="{{fieldValues.username}}">
					</div>

					<div class="form-group py-3">
						<input type="password" name="password" id="passwordField" class="form-control form-control-sm"
							placeholder="Password">
						<small class="float-end py-2 showPasswordToggle">SHOW</small>
					</div>
					<input type="submit" value="Login" class="btn btn-primary w-100 submit-btn">
				</form>
			</div>

		</div>
	</div>
	<div class='col-md-4'></div>
</div>

<script src="{% static 'js/register.js' %}"></script>

{% endblock %}

templates/authentication/register.html
{% extends 'base_auth.html' %}
{% load static %}

{% block content %}
<div class='row'>
	<div class='col-md-4'></div>
	<div class='col-md-4'>
		<div class="card mt-5">

			<div class="card-body">
				<div class="card-title py-3">
					<h4>Register for a free account</h4>
				</div>
				{% include 'partials/_messages.html' %}
				<form action="{% url 'authentication:register' %}" method="post">
					{% csrf_token %}
					<div class="form-group">
						<input type="text" name="username" id="usernameField" class="form-control form-control-sm"
							placeholder="Username" value="{{fieldValues.username}}">
					</div>
					<div class="invalid_feedback invalid-feedback " style="display: none"></div>
					<p class="text-sm text-success usernameSuccessOutput"></p>
					<div class="form-group my-3">
						<input type="email" name="email" id="emailField" class="form-control form-control-sm"
							placeholder="Email" value="{{fieldValues.email}}">
					</div>
					<p class="text-sm text-success emailSuccessOutput"></p>

					<div class="emailFeedBackArea invalid-feedback" style="display: none"></div>
					<div class="form-group">
						<input type="password" name="password" id="passwordField" class="form-control form-control-sm"
							placeholder="Password">
						<small class="float-end py-2 showPasswordToggle">SHOW</small>
					</div>
					<input type="submit" value="Register" class="btn btn-primary w-100 submit-btn">
				</form>
			</div>

		</div>
	</div>
	<div class='col-md-4'></div>
</div>

<script src="{% static 'js/register.js' %}"></script>

{% endblock %}

templates/authentication/reset_password.html
{% extends 'base_auth.html' %}

{% block content %}

	<div class=card>
	<div class="card-body">
	</div>
	</div>

{% endblock %}

templates/authentication/set_newpassword.html
{% extends 'base_auth.html' %}

{% block content %}

	<div class=card>
	<div class="card-body">
	</div>
	</div>

{% endblock %}